version: '3.3'

services:
  nginx:
      build:
        context: .
        dockerfile: ./docker/nginx.dockerfile  
      container_name: nginx
      ports:
      - "80:80"
      volumes:
      - static_volume:/app/staticfiles
      networks:
      - django-cine-network
      depends_on:
      - web
      restart: on-failure

  web:
    build:
      context: .
      dockerfile: ./docker/django-cine.dockerfile 
    ports:
      - "8000"
    env_file:
      - ./.envs/.django.prod
    volumes:
    - static_volume:/app/staticfiles
    networks:
    - django-cine-network
    depends_on:
    - db
    restart: on-failure
  
  db:
    image: postgres:13.4-alpine
    env_file:
      - ./.envs/.db.prod
    volumes:
    - db_data:/var/lib/postgresql/data
    networks:
    - django-cine-network
    restart: on-failure

networks: 
    django-cine-network:
        driver: bridge

volumes:
  static_volume:
  db_data: