# Generated by Django 3.2.7 on 2021-09-14 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('sinopse', models.TextField()),
                ('trailer', models.URLField(blank=True, null=True)),
                ('duracao', models.TimeField()),
                ('dublado', models.BooleanField()),
                ('legendado', models.BooleanField()),
                ('formato_2D', models.BooleanField()),
                ('formato_3D', models.BooleanField()),
                ('indicacao', models.CharField(choices=[('L', 'Livre'), ('10', '10 Anos'), ('14', '14 Anos'), ('16', '16 Anos'), ('18', '18 Anos')], max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_filme', to='catalogo.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('ativa', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('ativa', models.BooleanField()),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filme_sessao', to='catalogo.filme')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala_sessao', to='catalogo.sala')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
            },
        ),
    ]
