# Generated by Django 3.2.7 on 2021-09-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filme',
            name='em_breve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Comédia'), (2, 'Terror'), (3, 'Sci-fi'), (4, 'Ação'), (5, 'Infantil'), (6, 'Romance'), (7, 'Suspense'), (8, 'Drama'), (9, 'Documentário')]),
        ),
        migrations.AlterField(
            model_name='filme',
            name='dublado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filme',
            name='duracao',
            field=models.TimeField(verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='formato_2D',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filme',
            name='formato_3D',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filme',
            name='indicacao',
            field=models.CharField(choices=[('L', 'Livre'), ('10', '10 Anos'), ('14', '14 Anos'), ('16', '16 Anos'), ('18', '18 Anos')], max_length=10, verbose_name='Indicação'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='legendado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
