# Generated by Django 3.2.7 on 2021-09-14 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20210914_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessao',
            old_name='data_hora',
            new_name='data_hora_final',
        ),
        migrations.AddField(
            model_name='sessao',
            name='data_hora_inicial',
            field=models.DateTimeField(default='2021-09-14 16:00:40'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessao',
            name='filme',
            field=models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.CASCADE, related_name='filme_sessao', to='catalogo.filme'),
        ),
    ]
