# Generated by Django 3.2.7 on 2021-09-15 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20210914_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='sala',
            field=models.ForeignKey(limit_choices_to={'ativa': True}, on_delete=django.db.models.deletion.CASCADE, related_name='sala_sessao', to='catalogo.sala'),
        ),
    ]
